# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438c2e7dc0f26951c9ce1a31b06c9740d015fa798290f557d0f8953723b530d60d52160216d584903ad0a860347fa47d5a1e43d033c9580d8a946c2c5959ac9c

test:
  secret_key_base: 2be45113e3cce4bbb642c764c92d67e06ab3a692052e22e6b981c888a6c48a6aa0b1aa1db6f2ebb565d6695b31bf5761111b07a0ec7daf84c99afc953c17df05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
